### ISSUE TITLE
license of this repository

### ISSUE THREAD

**Issue by ronbar123** [haruelrovix/osg-wpf#2]
Hi,
I would like to use this project. What is the license of this repository? MIT? BSD? other?

**Comment by haruelrovix** [comment]
Hi @ronbarnoy !

I created this repo 3 years ago during my time learning OpenSceneGraph. I'm surprised there is someone came here 😁

Could you please create a Pull Request with license that suitable for your needs? I'll approve it anyway.

Thanks!

**Comment by ronbar123** [comment]
Hi @haruelrovix ,
Thank you for your quick reply, I sent you a PR from my fork as you requested

**Comment by haruelrovix** [comment]
Thank you so much @ronbarnoy ! 💯
